import type { MonetizationOffer } from './monetization';

export const monetizationSeed: MonetizationOffer[] = [
  {
    id: 'banking-premium-001',
    slug: 'premium-banking-offer',
    entity_type: 'bank_product',
    title: 'Premium Banking Offer',
    description: 'Премиальный банковский продукт для digital-команд, агентств и предпринимателей.',
    short_description: 'Банковский продукт с высоким commercial intent и RevShare-моделью.',
    url: 'https://example.com/banking',
    affiliate_url: 'https://example.com/banking?ref=grog',
    cta_label: 'Получить доступ',
    category: 'banking',
    placement: 'homepage_footer',
    price_model: 'revshare',
    pricing: 'free',
    commission_rate: 0.2,
    featured: true,
    verified: true,
    status: 'active',
    tags: ['bank', 'cashback', 'business', 'finance'],
    country: 'RU',
    device_type: 'all',
    click_count: 0,
    impression_count: 0,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
  },
  {
    id: 'sponsor-001',
    slug: 'sponsor-hero-placement',
    entity_type: 'sponsor',
    title: 'Sponsored Hero Placement',
    description: 'Нативное спонсорское размещение на главной странице с премиальной подачей.',
    short_description: 'Премиум слот для спонсора проекта.',
    url: 'https://example.com/sponsor',
    affiliate_url: 'https://example.com/sponsor?ref=grog',
    cta_label: 'Стать спонсором',
    category: 'sponsorship',
    placement: 'homepage_hero',
    price_model: 'fixed + revshare',
    pricing: 'custom',
    commission_rate: 0.15,
    featured: true,
    verified: true,
    status: 'active',
    tags: ['sponsor', 'brand', 'premium'],
    country: 'RU',
    device_type: 'all',
    click_count: 0,
    impression_count: 0,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
  },
  {
    id: 'advertiser-001',
    slug: 'advertiser-sidebar-slot',
    entity_type: 'advertiser',
    title: 'Sidebar Advertising Slot',
    description: 'Рекламный слот для рекламодателей с фокусом на высокий intent и прозрачную аналитику.',
    short_description: 'Рекламный слот для performance-брендов.',
    url: 'https://example.com/advertise',
    affiliate_url: 'https://example.com/advertise?ref=grog',
    cta_label: 'Разместить рекламу',
    category: 'advertising',
    placement: 'sidebar',
    price_model: 'fixed',
    pricing: 'custom',
    commission_rate: 0.1,
    featured: false,
    verified: true,
    status: 'active',
    tags: ['advertiser', 'ads', 'performance'],
    country: 'RU',
    device_type: 'desktop',
    click_count: 0,
    impression_count: 0,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
  },
];
